name: Post a welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Post that welcome comment
    runs-on: ubuntu-latest
    steps: 
      - run: gh pr comment $PR_URL --body "Welcome to the repo!"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
